// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/org-form/NovaOrg.tsx": () => import("../components/mockups/org-form/NovaOrg.tsx")
};
